# .github/workflows/pages.yml
name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]     # ← main に push したら発火

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      # ↓ これで **run: …** のカレントディレクトリがすべて ./vue-app になる
      run:
        working-directory: ./vue-app

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ./vue-app/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Check Tailwind dependencies
        run: npm ls tailwindcss @tailwindcss/postcss

      - name: Build
        run: npm run build       # → ./vue-app/dist に出力

      - name: Upload dist
        uses: actions/upload-pages-artifact@v3
        with:
          path: vue-app/dist     # ← ルートから見た相対パスで指定

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
